ALTER TABLE song ADD COLUMN IF NOT EXISTS duration VARCHAR(20);

ALTER TABLE comment ADD COLUMN IF NOT EXISTS edit_token VARCHAR(40);
ALTER TABLE comment ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
